[package]
name = "rusoda"
version = "0.1.0"
authors = ["Daogang Tang <daogangtang@live.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.5"
rand = "^0.3.17"
tiny-keccak = "^1.3.1"
redis = "0.9"
sapper = {path = "../sapper/"}
sapper_std = {path = "../sapper/library/sapper_std"}
rustorm = {path = "../rustorm", features = ["with-postgres"]}
rustorm_dao = {path = "../rustorm/dao"}
rustorm_codegen = {path = "../rustorm/codegen"}
uuid = {features = ["serde", "v4"], version = "0.5.1"}
chrono = {features = ["serde"], version = "0.4"}
serde = "*"
serde_json = "*"
serde_derive = "*"
serde_urlencoded = "*"
ammonia = "^1.0.1"
hyper-native-tls = "^0.2.4"
hyper = "^0.10.13"
comrak = "^0.2.4"

[[bin]]
name = "page_forum_bin"
path = "src/page_forum_bin.rs"

